/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef KV_CONSTANTS_H
#define KV_CONSTANTS_H

#include "KV_types.h"

namespace keyvalue {

class KVConstants {
 public:
  KVConstants();

  std::string KV_EM_GENERIC;
  std::string KV_EM_OUT_OF_MEM;
  std::string KV_EM_FILE_NOT_EXIST;
  std::string KV_EM_FILE_PERM_ERROR;
  std::string KV_EM_DISK_FULL;
  std::string KV_EM_FILE_EXIST;
  std::string KV_EM_FILE_IN_USE;
  std::string KV_EM_FILE_EOF;
  std::string KV_EM_READ_FAIL;
  std::string KV_EM_WRITE_FAIL;
  std::string KV_EM_FILE_FAIL;
  std::string KV_EM_ACCESS_OUT_OF_PAGE;
  std::string KV_EM_PAGE_DAMAGE;
  std::string KV_EM_CTRLFILE_DAMAGE;
  std::string KV_EM_OVERFLOW;
  std::string KV_EM_INDEX_BROKEN;
  std::string KV_EM_INDEX_UNQIUE_VIOLATION;
  std::string KV_EM_NOT_LOCKED;
  std::string KV_EM_TOO_MANY_ROWLOCK;
  std::string KV_EM_TOO_MANY_SESSION;
  std::string KV_EM_NOT_SUPPORT;
  std::string KV_EM_EXCEED_LIMIT;
  std::string KV_EM_CORRUPTED_LOGFILE;
  std::string KV_EM_MISSING_LOGFILE;
  std::string KV_EM_DUP_TABLEID;
  std::string KV_EM_INVALID_BACKUP;
  std::string KV_EM_LOCK_TIMEOUT;
  std::string KV_EM_LOCK_FAIL;
  std::string KV_EM_SYNTAX_ERROR;
  std::string KV_EM_ROW_TOO_LONG;
  std::string KV_EM_NONEINDEX;
  std::string KV_EM_DUPINDEX;
  std::string KV_EM_COLDEF_ERROR;
  std::string KV_EM_CANCELED;
  std::string KV_EM_CORRUPTED;
  std::string KV_EM_TABLEDEF_ERROR;
  std::string KV_EM_INVALID_COL_GRP;
  std::string KV_EM_NO_DICTIONARY;
  std::string KV_EM_UNSUPPORTED_ENCODE;
  std::string KV_EM_CONNCETION_REFUSED;
  std::string KV_EM_TBLDEF_NOT_MATCH;
  std::string KV_EM_TBLDEF_ACCESS_FAIL;
  std::string KV_EM_TABLE_NOT_EXIST;
  std::string KV_EM_KEY_ERROR;
  std::string KV_EM_KET_NOT_MATCH;
  std::string KV_EM_COL_NOT_EXIST;
  std::string KV_EM_UNSUPPORTED_OP;
  std::string KV_EM_COLTYPE_NOT_MATCH;
  std::string KV_EM_TOO_FEW_COL;
  std::string KV_EM_TOO_MANY_COL;
  std::string KV_EM_KEY_EXIST;
  std::string KV_EM_KEY_NOT_EXIST;
  std::string KV_EM_UNKNOWN_HOST;
  std::string KV_EM_TIMEOUT;
  std::string KV_EM_UNSUPPORTED_DATATYPE;
  std::string KV_EM_ILLEGAL_PARAMETER;
  std::string KV_EM_COL_NOT_NULLABLE;
  std::string KV_EM_DUP_COL;
  std::string KV_EM_CONFLICT_COLVALUE;
  std::string KV_EM_VALUE_OVERFLOW;
  std::string KV_EM_GENERAL_ERROR;
  std::string KV_EM_TABLE_IN_DROPPING;
  std::map<ErrCode::type, std::string>  errmsgMap;
};

extern const KVConstants g_KV_constants;

} // namespace

#endif
